import Head from "next/head";
import Navbar from "./components/navbar";
import "./globals.css";
import EndNote from "./components/footer";

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Head>
      <title>Tenzin Loden</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="stylesheet" href="https://use.typekit.net/wgl4zxx.css"/>
    </Head>
      <body >
        {/* Layout UI */}
        {/* Place children where you want to render a page or nested layout */}
        <main>
          <div className="m-1 sm:m-1 md:ml-10 md:mr-20 md:mt-10 2xl:ml-30 2xl:mr-40 2xl:mt-12">
          <Navbar />
          <EndNote />
          <div>
          {children}
          </div>
          </div>
        </main>
      </body>
    </html>
  )
}